name: Deploy src to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:     # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    # Forces any un-updated actions to run on Node.js 24 safely
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout
        uses: actions/checkout@v6 # Bumped to v6 for native Node 24 support

      - name: Fetch fresh API data
        run: |
          curl -k -L 'https://code.golf/scores/all-holes/all-langs/all' -o ./src/solutions.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4